/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6a6b085d-e7de-4d94-b687-774c2367989d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_JzPGZTCaz",
    "aws_user_pools_web_client_id": "7fgtp6pigomfb742f7c68r1ln7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://ivlfsstk4jhsdo5wihkkdzb6bi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fnz74ldqo5bgrfb7ho6p3wgr2i",
    "aws_user_files_s3_bucket": "amplifyreactgraphql16c48c02011242629d68df9b9605104520-staging",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
